# Generated by Django 4.2.7 on 2025-06-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Book Title')),
                ('author', models.CharField(max_length=100, verbose_name='Author')),
                ('cover', models.URLField(blank=True, null=True, verbose_name='Cover Image URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateField(blank=True, null=True, verbose_name='Created At')),
                ('updated_at', models.DateField(blank=True, null=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ['-created_at'],
            },
        ),
    ]
